In [1]:
import numpy as np
import pandas as pd
from sklearn.utils import resample

In [ ]:
#set the random seeed for reproductivity ...sets a fixed starting point for NumPy's random number generator so that the same random numbers are produced every time the code runs.

np.random.seed(123)

In [3]:
n_samples = 1000
n_class_0 = 900  # Majority
n_class_1 = 100

In [ ]:
# create dataframe with imbalanced dataset
##pd.DataFrame() creates a table-like data structure using Pandas.
##np.random.normal() generates random numbers from a normal distribution with specified mean (loc) and standard deviation (scale).
##The 'target' column is created to indicate the class labels, where class 0 is labeled as 1 and class 1 is labeled as 0. 

class_0 = pd.DataFrame({
    'feature1': np.random.normal(0, 1, n_class_0),
    'feature2': np.random.normal(0, 1, n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature1': np.random.normal(1, 1, n_class_1),
    'feature2': np.random.normal(1, 1, n_class_1),
    'target': [1] * n_class_1
})

In [ ]:
##pd.concat() is used to concatenate the two dataframes (class_0 and class_1) along the rows (axis=0). The reset_index(drop=True) is used to reset the index of the resulting dataframe, dropping the old index and creating a new one. This ensures that the index is sequential and does not retain the original indices from the concatenated dataframes.

df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [ ]:
##value_counts() is a Pandas function that counts the occurrences of each unique value in a Series. In this case, it is used to count the occurrences of each class label in the 'target' column of the dataframe df. This will help us understand the distribution of classes in our imbalanced dataset.

df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [6]:
# 3. Data ko split karein (Target ke basis par)
df_majority = df[df['target'] == 0]
df_minority = df[df['target'] == 1]

In [ ]:

##resample() is a function from the sklearn.utils module that allows you to perform resampling operations on your data. In this case, it is used to upsample the minority class (class 0) by randomly sampling with replacement from the minority class dataframe (df_minority) until we have the same number of samples as the majority class (n_class_1). The random_state parameter is set to 123 to ensure reproducibility of the results.


##The resampled minority class dataframe (df_minority_upsampled) will contain the same number of samples as the majority class, effectively balancing the dataset. The replace=True parameter allows for sampling with replacement, meaning that the same sample from the minority class can be selected multiple times to achieve the desired number of samples.


df_minority_upsampled = resample(df_minority, 
                                 replace=True,     # Duplicate rows banane ke liye
                                 n_samples=len(df_majority), # Isko 900 kar do
                                 random_state=42)

In [13]:
df_minority_upsampled.shape

(900, 3)

In [14]:
df_minority_upsampled.head()

     feature1  feature2  target
951  0.125854  0.843917       1
992  1.196570  0.397425       1
914  0.932170  1.998053       1
971  1.272825  2.034197       1
960  1.870056  0.550485       1

In [15]:
df_minority_upsampled.tail()

     feature1  feature2  target
952  0.188902  1.189189       1
965  2.919526  0.980541       1
976  1.810326  2.604614       1
942  2.621531  1.168229       1
974  0.160887  1.489203       1

In [16]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

In [18]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [ ]:
## Downsampling: Majority class se randomly samples ko remove karna, taki dono classes ke samples ka number same ho jaye. Isse model ko dono classes ke baare mein sikhne ka mauka milta hai, lekin data loss ho sakta hai.