### Data Encoding

1.Nominal Encoding/OHE Encoding (One Hot Encoding)  
2.Label and Ordinal Encoding  
3.Target Guided Ordinal Encoding

Data Encoding is the process of converting categorical data into a format that can be easily understood and processed by machine learning algorithms. Categorical data can be of two types: nominal and ordinal.

### 1. Nominal Encoding / OHE Encoding (One Hot Encoding)

In this technique, we represent categorical data as numerical data.

In this method, each category is represented as a binary vector.

```
Color_Red   Color_Green   Color_Blue
1           0             0
0           1             0
0           0             1
```

there are some disadvantages of this method:

1. It can lead to a high-dimensional feature space, especially when there are many categories.
2. It can lead to multicollinearity, which can affect the performance of some machine learning algorithms.

In [ ]:

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
## create a sample dataframe

df= pd.DataFrame({'color':['red','blue','green','red','blue']}) 
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [5]:
## create an instance of the OneHotEncoder
encoder = OneHotEncoder()

In [7]:
## perform fit and transform the data
# 
# the fit method learns the unique categories in the 'color' column, and the transform method converts the categorical values into a binary matrix. The toarray() method is used to convert the sparse matrix output from the encoder into a dense array format for easier visualization.


encoded=encoder.fit_transform(df[['color']]).toarray()

In [9]:
import pandas as pd
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())
encoder_df.head()

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0